DROP TABLE IF EXISTS "entry";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "address";
DROP TABLE IF EXISTS "buyer";
DROP TABLE IF EXISTS "product";

DROP TABLE IF EXISTS "inventory"; 
DROP TABLE IF EXISTS "user";