// Code generated by sqlc. DO NOT EDIT.
// source: buyer.sql

package db

import (
	"context"
)

const createBuyer = `-- name: CreateBuyer :one
INSERT INTO "buyer" (
  name,
  address
) VALUES (
  $1, $2
)
RETURNING id, name, address, update_at, created_at
`

type CreateBuyerParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
}

func (q *Queries) CreateBuyer(ctx context.Context, arg CreateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, createBuyer, arg.Name, arg.Address)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuyer = `-- name: GetBuyer :one
SELECT id, name, address, update_at, created_at FROM "buyer"
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetBuyer(ctx context.Context, name string) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyer, name)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBuyerForUpdate = `-- name: GetBuyerForUpdate :one
SELECT id, name, address, update_at, created_at FROM "buyer"
WHERE name = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetBuyerForUpdate(ctx context.Context, name string) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyerForUpdate, name)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBuyer = `-- name: ListBuyer :many
SELECT id, name, address, update_at, created_at FROM "buyer"
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListBuyerParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBuyer(ctx context.Context, arg ListBuyerParams) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, listBuyer, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Buyer{}
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.UpdateAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuyer = `-- name: UpdateBuyer :one
UPDATE "buyer"
SET address = $2
WHERE id = $1
RETURNING id, name, address, update_at, created_at
`

type UpdateBuyerParams struct {
	ID      int64  `json:"id"`
	Address string `json:"address"`
}

func (q *Queries) UpdateBuyer(ctx context.Context, arg UpdateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, updateBuyer, arg.ID, arg.Address)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}
