// Code generated by sqlc. DO NOT EDIT.
// source: inventory.sql

package db

import (
	"context"
)

const addInventoryAmount = `-- name: AddInventoryAmount :one
UPDATE "inventory"
SET amount = amount + $1
WHERE id = $2
RETURNING id, type, name, amount, update_at, created_at
`

type AddInventoryAmountParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddInventoryAmount(ctx context.Context, arg AddInventoryAmountParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, addInventoryAmount, arg.Amount, arg.ID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO "inventory" (
  type,
  name,
  amount
) VALUES (
  $1, $2, $3
) RETURNING id, type, name, amount, update_at, created_at
`

type CreateInventoryParams struct {
	Type   string `json:"type"`
	Name   string `json:"name"`
	Amount int64  `json:"amount"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory, arg.Type, arg.Name, arg.Amount)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :one
SELECT id, type, name, amount, update_at, created_at FROM "inventory"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInventory(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInventoryForUpdate = `-- name: GetInventoryForUpdate :one
SELECT id, type, name, amount, update_at, created_at FROM "inventory"
WHERE id = $1 LIMIT 1
FOR NO KEY UPDATE
`

func (q *Queries) GetInventoryForUpdate(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryForUpdate, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT id, type, name, amount, update_at, created_at FROM "inventory"
WHERE name = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListInventoryParams struct {
	Name   string `json:"name"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, listInventory, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Amount,
			&i.UpdateAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one
UPDATE "inventory"
SET amount = $2
WHERE id = $1
RETURNING id, type, name, amount, update_at, created_at
`

type UpdateInventoryParams struct {
	ID     int64 `json:"id"`
	Amount int64 `json:"amount"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, updateInventory, arg.ID, arg.Amount)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Amount,
		&i.UpdateAt,
		&i.CreatedAt,
	)
	return i, err
}
