// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Address struct {
	ID        int64     `json:"id"`
	BuyerID   int64     `json:"buyer_id"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type Buyer struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	UpdateAt  time.Time `json:"update_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID          int64     `json:"id"`
	OrderID     int64     `json:"order_id"`
	InventoryID int64     `json:"inventory_id"`
	Amount      int64     `json:"amount"`
	CreatedAt   time.Time `json:"created_at"`
}

type Inventory struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	Amount    int64     `json:"amount"`
	UpdateAt  time.Time `json:"update_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID        int64     `json:"id"`
	BuyerID   int64     `json:"buyer_id"`
	ProductID int64     `json:"product_id"`
	Amount    int64     `json:"amount"`
	Unit      string    `json:"unit"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	Amount    int64     `json:"amount"`
	Unit      string    `json:"unit"`
	Price     int64     `json:"price"`
	UpdateAt  time.Time `json:"update_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
	UpdateAt       time.Time `json:"update_at"`
	CreatedAt      time.Time `json:"created_at"`
}
